- README.md
- codec.js
- example.js
- index.js
- lib/dat-helper.js
- schemas/content.json
- schemas/dbitem.json
- schemas/profile.json
This PR is based on the feedback received after releasing v0.2.0. It decouples what is stored on the db from the dat.json metadata. Also adds some small refactor work.
> Feedback patch: 0.2.x

- codec.js
- example.js
- index.js
- lib/utils.js
- package-lock.json
- schemas/content.json
- schemas/dbitem.json
- schemas/profile.json
- tests/index.js
> Fix: url as string in dat.json

- lib/dat-helper.js
- package-lock.json
- package.json
- tests/index.js
This PR closes #26 
This fixes a situation where `mirror-folder` was copying multiple `.dat` files which ends up blocking the process.
> fix: sdk hang

- .travis.yml
> Update: add windows to travis

- index.js
- schemas/content.json
- schemas/profile.json
- tests/index.js
- validation.js
This PR closes #30 
It adds a better validation strategy using avro [logical types](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) and custom validations like [this](https://stackoverflow.com/questions/37279096/data-validation-in-avro/37282006#37282006).
> Update: improve validations

- index.js
> Update: add missing return

- index.js
- package-lock.json
- package.json
> Update: use npm version of level-auto-index

- index.js
- tests/index.js
> Update: add main param to init method

- codec.js
- index.js
- schemas/content.json
- schemas/profile.json
- tests/index.js
This PR should close #38  
schemas are up to date according new module spec.
tests are updated according new spec too.
> update: module spec 0.2.0

- .travis.yml
- README.md
- codec.js
- example.js
- index.js
- lib/dat-helper.js
- package-lock.json
- package.json
- schemas/content.json
- schemas/profile.json
- tests/index.js
- validation.js
This is an ongoing PR adding `register` and `verify` methods. Feedback is welcome.
> Ongoing: v0.3.0

- index.js
- tests/index.js
> update tests: set profile module

- index.js
- tests/index.js
> Fix: register duplicates

- index.js
- tests/index.js
> Update: add dat prefix on contents urls + tests

- index.js
- lib/utils.js
- tests/index.js
> Update: init can receive authors, parents, follows or contents

- index.js
- tests/index.js
This closes #60 
Also replace `toString('hex')` usage with `DatEncoding`.
> Update: add dat prefix on url. 

- index.js
- package-lock.json
- tests/index.js
> New: follow and unfollow methods

- index.js
- tests/index.js
> Allow modify parents fields

- validation.js
> Update: dat prefix required

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- tests/index.js
This PR adds a new changelog file and also a tool to manage it, called [chan](https://github.com/geut/chan).
> Added: changelog

- CHANGELOG.md
- package-lock.json
- package.json
> Update: use latest corestore-swarm-networking

- CHANGELOG.md
- README.md
- index.js
- package-lock.json
- package.json
- tests/index.js
> implicit ready

- CHANGELOG.md
- index.js
- package.json
- tests/index.js
> extra params throws validationerror

- CHANGELOG.md
- schemas/content.json
> Fix: only accept versioned parents

- CHANGELOG.md
- index.js
- tests/index.js
this works locally, let's see what CI says
> fix ignored leveldb open errors. closes #112

- CHANGELOG.md
- schemas/validation.js
- tests/index.js
> Fix: title limit

- CHANGELOG.md
- index.js
- lib/utils.js
- package-lock.json
- package.json
- schemas/content.json
- schemas/profile.json
- schemas/validation.js
- tests/index.js
This PR closes #118 and #121 
Notes: `main` property does not have any effect on `init`. Although, it can be updated via `set`, this will trigger validations.
> Update: add avatar and main checks

- CHANGELOG.md
- index.js
- tests/index.js
> Fix: uncaught error set

- CHANGELOG.md
- README.md
- index.js
> Fix: inconsistent clone output

- CHANGELOG.md
- index.js
- tests/index.js
> Update: allow main empty

- CHANGELOG.md
- index.js
- lib/parse-url.js
- package-lock.json
- package.json
This should close #134 
Replaced parse-dat-url with url-parse following the same strategy from [dat-archive-web](https://github.com/RangerMauve/dat-archive-web/blob/master/DatArchive.js#L469)
> Update: url parse

- CHANGELOG.md
- index.js
- tests/index.js
> Change: rename module to rawJSON on clone method

- CHANGELOG.md
- README.md
- index.js
- package-lock.json
- package.json
- tests/index.js
This PR closes #90 
In summary, it adds a new option to `delete` method, called `force` which accepts a boolean value. If `true` it will move the module folder to the trash bin.
> Update: delete force option

- CHANGELOG.md
- README.md
- index.js
- tests/index.js
> Update: check main on publish

- CHANGELOG.md
- lib/dat-helper.js
- package-lock.json
- package.json
> Update: hypercore-crypto

- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE
- README.md
- index.js
- lib/dat-helper.js
- lib/parse-url.js
- package-lock.json
- package.json
- tests/childProcess2.js
- tests/index.js
Due to the changes in the branch names on other repo's, links were broken. This is a small PR to fix those URLs.
> Update broken links

- CHANGELOG.md
- index.js
This PR checks for the drive closing status before actual close.
> Update: check drive status before closing

- CHANGELOG.md
- README.md
- index.js
- lib/errors.js
- package-lock.json
- package.json
- tests/index.js
This PR adds a new custom error that can occur with any problem around watching the FS using mirror folder.
Related to #173. This new error is propagated usually when the sdk is interacting with antivirus or any other software doing file watching over the modules. Apps can decide then what to do with it.
> Update: new error EBUSYError

- CHANGELOG.md
- README.md
- index.js
- lib/errors.js
- lib/spec.js
- lib/utils.js
- package-lock.json
- package.json
- tests/index.js
A tiny integration to simplify maintaining the `sdk-js` when the `@p2pcommons/specs` are updated.
Closes #157
> Add dynamic versioning

- CHANGELOG.md
- package-lock.json
- package.json
trying a new release scheme, first we create this new version, after approval we publish.
> New release: 0.6.2

- CHANGELOG.md
- lib/utils.js
- tests/index.js
> Fix: use spec.module

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> release 0.6.3

- CHANGELOG.md
- package.json
> Update: version bump and changelog
